baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Photoalbum Test'

[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[params]
  defaultTheme = "dark"

